#  https://github.com/nabilnalakath/flutter-githubaction/blob/master/.github/workflows/main.yml
on: push
name: Test, Build and Release iOS
jobs:
  build:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - run: echo ${{github.ref}}
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8.0.212'
      #        java-version: '1.8.0_212-release-1586-b04)' not working
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.8'
      - run: flutter pub get
      #    - run: flutter clean
      #    - run: flutter pub cache repair
      - run: flutter doctor -v
      - run: flutter test
#      START - iOS simulator build
#        NOTE: iOS simulator requires a different build
#      - run: xcodebuild -list -workspace ios/Runner.xcworkspace
#      - run: pwd
#      - run: xcodebuild -sdk iphonesimulator -workspace ios/Runner.xcworkspace/ -scheme Runner -configuration Debug CONFIGURATION_BUILD_DIR=$PWD/build
#      END - iOS simulator build
      - run: flutter build ios --release --no-codesign
      - name: Prepare tag for release
        id: step_tag
        uses: mcpierce/github-commit-timestamp-tagger@master
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          base_version: "v0.0.0"
          #        tag_name: "how to use return vars"
      - run: ls -l
      - run: ls -R
      - run: zip -r output_file.zip build
      - name: Push iOS to Releases
        uses: ncipollo/release-action@v1
        with:
          #artifacts: "/Users/runner/runners/2.165.2/work/flutter_app/flutter_app/build/ios/iphoneos/Runner.app"
          artifacts: "output_file.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{steps.step_tag.outputs.tag_name}}
#        tag: "v0.0.1" New tag

