#  https://github.com/nabilnalakath/flutter-githubaction/blob/master/.github/workflows/main.yml
on: push
name: Test, Build and Release iOS
jobs:
  build:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - run: echo "::set-env name=TAG_BRANCHE_NAME::v0.0.0_${GITHUB_REF##*/}_ios"
      - run: echo $TAG_BRANCHE_NAME
      - run: echo ${{github.ref}} #Test
      - run: echo ${GITHUB_REF##*/}  #Test
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8.0.212'
      #        java-version: '1.8.0_212-release-1586-b04)' not working
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.8'
      - run: flutter pub get
      #    - run: flutter clean
      #    - run: flutter pub cache repair
      - run: flutter doctor -v
      - run: flutter test
      - name: Build simulator app
  #      CMD to create simulator .app
        run: |
          xcodebuild -list -workspace ios/Runner.xcworkspace
          pwd
          xcodebuild -sdk iphonesimulator -workspace ios/Runner.xcworkspace/ -scheme Runner -configuration Debug CONFIGURATION_BUILD_DIR=$PWD/build_ios_simulator
          zip -r build/build_ios_simulator.ipa build_ios_simulator/Runner.app
#            - run: xcodebuild -sdk iphonesimulator -workspace ios/Runner.xcworkspace/ -scheme Runner -configuration Debug
#      Test above
  #    - run: xcodebuild -list -workspace ios/Runner.xcworkspace
  #    - run: pwd
#      Test code - START
#      - run: xcodebuild -sdk iphonesimulator -workspace ios/Runner.xcworkspace/ -scheme Runner -configuration Debug
#      Test code - END
  #    - run: xcodebuild -sdk iphonesimulator -workspace ios/Runner.xcworkspace/ -scheme Runner -configuration Debug CONFIGURATION_BUILD_DIR=$PWD/build
#      - run: xcrun xcodebuild \ -scheme $XCODE_SCHEME \ -project $XCODE_PROJECT \ -configuration Debug \ -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=9.1' \ -derivedDataPath \ build
      - name: Build release app
        run: flutter build ios --release --no-codesign
      - name: Prepare tag for release
        env:
          TAG_BRANCHE_NAMEe: master
        id: step_tag
        uses: mcpierce/github-commit-timestamp-tagger@master
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          base_version: ${{env.TAG_BRANCHE_NAME}}
          #        tag_name: "how to use return vars"
      - run: ls -l
      #- run: cd build
      #- run: ls -l
      - run: ls -R
#      - run: sudo apt install zip unzip
#      Not working
      - run: zip -r output_file.zip build
      - name: Push iOS to Releases
        uses: ncipollo/release-action@v1
        with:
          #artifacts: "/Users/runner/runners/2.165.2/work/flutter_app/flutter_app/build/ios/iphoneos/Runner.app"
          artifacts: "output_file.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{steps.step_tag.outputs.tag_name}}
#        tag: "v0.0.1" New tag

