#  https://github.com/nabilnalakath/flutter-githubaction/blob/master/.github/workflows/main.yml
on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - run: echo "::set-env name=TAG_BRANCHE_NAME::v0.0.0_android_${GITHUB_REF##*/}"
    - run: echo $TAG_BRANCHE_NAME
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8.0.212'
#        java-version: '1.8.0_212-release-1586-b04)' not working
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.13+hotfix.8'
    - run: flutter pub get
#    - run: flutter clean
#    - run: flutter pub cache repair
    - run: flutter doctor -v
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: Prepare tag for release
      id: step_tag
      uses: mcpierce/github-commit-timestamp-tagger@master
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
#        base_version: "v0.0.0"
        base_version: ${{env.TAG_BRANCHE_NAME}}
      #        tag_name: "how to use return vars"
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{steps.step_tag.outputs.tag_name}}
#        tag: "v0.0.1" New tag

