#  https://github.com/nabilnalakath/flutter-githubaction/blob/master/.github/workflows/main.yml
on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8.0.212'
#        java-version: '1.8.0_212-release-1586-b04)' not working
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.13+hotfix.8'
    - run: flutter pub get
#    - run: flutter clean
#    - run: flutter pub cache repair
    - run: flutter doctor -v
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: Create tag
      uses: mosfetlang/dev-tagger-action@v1
        with:
          tag-prefix: 'my-tag-'
          origin: 'origin'
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}
        tag: $newTag

# https://github.com/marketplace/actions/flutter-cli
#on: push
#name: build and test app
#jobs:
#  build:
#    name: install dependencies
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: install dependencies
#        uses: steebchen/flutter@v1.0.0
#        with:
#          args: pub get
#
#      - name: check verbose
#        uses: steebchen/flutter@v1.0.0
#        with:
#          args: run --verbose
#
#      - name: clean project
#        uses: steebchen/flutter@v1.0.0
#        with:
#          args: clean
#
#      - name: repair cache
#        uses: steebchen/flutter@v1.0.0
#        with:
#          args: pub cache repair
#
#      - name: run tests
#        uses: steebchen/flutter@v1.0.0
#        with:
#          args: test
#
#      - name: build apk
#        uses: steebchen/flutter@v1.0.0
#        with:
#          args: build apk --release